# Basic linear algebra in Julia
Author: Andreas Noack Jensen (MIT) (http://www.econ.ku.dk/phdstudent/noack/)
(with edits from Jane Herriman)

First let's define a random matrix

In [1]:
A = rand(1:4,3,3)

3×3 Matrix{Int64}:
 4  4  3
 3  4  4
 3  2  2

Define a vector of ones

In [2]:
x = fill(1.0, (3,)) # = fill(1.0, 3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [3]:
# alternatively
ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

Notice that $A$ has type Array{Int64,2} but $x$ has type Array{Float64,1}. Julia defines the aliases Vector{Type}=Array{Type,1} and Matrix{Type}=Array{Type,2}. 

Many of the basic operations are the same as in other languages
#### Multiplication

In [4]:
b = A*x

3-element Vector{Float64}:
 11.0
 11.0
  7.0

#### Transposition
As in other languages `A'` is the conjugate transpose, or adjoint

In [5]:
A'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 4  3  3
 4  4  2
 3  4  2

and we can get the transpose with

In [6]:
transpose(A)

3×3 transpose(::Matrix{Int64}) with eltype Int64:
 4  3  3
 4  4  2
 3  4  2

#### Transposed multiplication
Julia allows us to write this without *

In [7]:
A'A

3×3 Matrix{Int64}:
 34  34  30
 34  36  32
 30  32  29

#### Solving linear systems 
The problem $Ax=b$ for ***square*** $A$ is solved by the \ function.

In [8]:
A\b

3-element Vector{Float64}:
 1.0
 1.0
 1.0

`A\b` gives us the *least squares solution* if we have an overdetermined linear system (a "tall" matrix)

In [9]:
Atall = rand(3, 2)

3×2 Matrix{Float64}:
 0.35378    0.742186
 0.944921   0.0141526
 0.0922638  0.404151

In [10]:
Atall\b

2-element Vector{Float64}:
 11.294540324535609
 10.653967068961553

and the *minimum norm least squares solution* if we have a rank-deficient least squares problem

In [11]:
v = rand(3)
rankdef = hcat(v, v)

3×2 Matrix{Float64}:
 0.0471883  0.0471883
 0.525467   0.525467
 0.833616   0.833616

In [12]:
rankdef\b

2-element Vector{Float64}:
 6.233969085490582
 6.233969085490582

Julia also gives us the minimum norm solution when we have an underdetermined solution (a "short" matrix)

In [13]:
bshort = rand(2)
Ashort = rand(2, 3)

2×3 Matrix{Float64}:
 0.661256  0.723633  0.875906
 0.686253  0.189021  0.977354

In [14]:
Ashort\bshort

3-element Vector{Float64}:
 0.1039090402698415
 0.9630088023848675
 0.03436264962784015

# The LinearAlgebra library

While much of linear algebra is available in Julia by default (as shown above), there's a standard library named `LinearAlgebra` that brings in many more relevant names and functions. In particular, it provides factorizations and some structured matrix types.  As with all packages, you can bring these additional features into your session with a `using LinearAlgebra`.

### Exercises

#### 10.1 
Take the inner product (or "dot" product) of a vector `v` with itself and assign it to variable `dot_v`.



In [15]:
v = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [18]:
using LinearAlgebra
dot_v = dot(v, v)

14

In [19]:
@assert dot_v == 14

#### 10.2 
Take the outer product of a vector v with itself and assign it to variable `outer_v`

In [21]:
outer_v = v * v'

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

In [22]:
@assert outer_v == [1 2 3
                    2 4 6
                    3 6 9]

In [24]:
cross_v = cross(v, v)

3-element Vector{Int64}:
 0
 0
 0

In [25]:
@assert cross_v == [0, 0, 0]

Please click on `Validate` on the top, once you are done with the exercises.